export const STUDENTS_REQUEST = "STUDENTS_REQUEST";
export const STUDENTS_SUCCESS = "STUDENTS_SUCCESS";
export const STUDENTS_ADD_REQUEST = "STUDENTS_ADD_REQUEST";
export const STUDENTS_ADD_SUCCESS = "STUDENTS_ADD_SUCCESS";
export const STUDENTS_UPDATE_REQUEST = "STUDENTS_UPDATE_REQUEST";
export const STUDENTS_UPDATE_SUCCESS = "STUDENTS_UPDATE_SUCCESS";
export const STUDENTS_DEL_REQUEST = "STUDENTS_DEL_REQUEST";
export const STUDENTS_DEL_SUCCESS = "STUDENTS_DEL_SUCCESS";
